/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PaymentImport } from './routes/payment'
import { Route as CartImport } from './routes/cart'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as EventsIndexImport } from './routes/events/index'
import { Route as CatalogIndexImport } from './routes/catalog/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as EventsSlugImport } from './routes/events/$slug'
import { Route as CheckoutSuccessImport } from './routes/checkout/success'
import { Route as CheckoutRecoverImport } from './routes/checkout/recover'
import { Route as CheckoutPendingImport } from './routes/checkout/pending'
import { Route as CheckoutCancelImport } from './routes/checkout/cancel'
import { Route as CatalogIdImport } from './routes/catalog/$id'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AdminSubmissionsImport } from './routes/admin/submissions'
import { Route as AdminSubmissionIssuesImport } from './routes/admin/submission-issues'
import { Route as AdminProductsImport } from './routes/admin/products'
import { Route as AdminMediaImport } from './routes/admin/media'
import { Route as AdminLoginImport } from './routes/admin/login'
import { Route as AdminEventsImport } from './routes/admin/events'
import { Route as AdminCouponsImport } from './routes/admin/coupons'
import { Route as EventsSlugCheckinImport } from './routes/events/$slug_.checkin'

// Create/Update Routes

const PaymentRoute = PaymentImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EventsIndexRoute = EventsIndexImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRoute,
} as any)

const CatalogIndexRoute = CatalogIndexImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const EventsSlugRoute = EventsSlugImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutSuccessRoute = CheckoutSuccessImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRecoverRoute = CheckoutRecoverImport.update({
  id: '/checkout/recover',
  path: '/checkout/recover',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutPendingRoute = CheckoutPendingImport.update({
  id: '/checkout/pending',
  path: '/checkout/pending',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutCancelRoute = CheckoutCancelImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRoute,
} as any)

const CatalogIdRoute = CatalogIdImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AdminSubmissionsRoute = AdminSubmissionsImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRoute,
} as any)

const AdminSubmissionIssuesRoute = AdminSubmissionIssuesImport.update({
  id: '/admin/submission-issues',
  path: '/admin/submission-issues',
  getParentRoute: () => rootRoute,
} as any)

const AdminProductsRoute = AdminProductsImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRoute,
} as any)

const AdminMediaRoute = AdminMediaImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRoute,
} as any)

const AdminLoginRoute = AdminLoginImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminEventsRoute = AdminEventsImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRoute,
} as any)

const AdminCouponsRoute = AdminCouponsImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRoute,
} as any)

const EventsSlugCheckinRoute = EventsSlugCheckinImport.update({
  id: '/events/$slug_/checkin',
  path: '/events/$slug/checkin',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentImport
      parentRoute: typeof rootRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsImport
      parentRoute: typeof rootRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsImport
      parentRoute: typeof rootRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaImport
      parentRoute: typeof rootRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsImport
      parentRoute: typeof rootRoute
    }
    '/admin/submission-issues': {
      id: '/admin/submission-issues'
      path: '/admin/submission-issues'
      fullPath: '/admin/submission-issues'
      preLoaderRoute: typeof AdminSubmissionIssuesImport
      parentRoute: typeof rootRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdImport
      parentRoute: typeof rootRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelImport
      parentRoute: typeof rootRoute
    }
    '/checkout/pending': {
      id: '/checkout/pending'
      path: '/checkout/pending'
      fullPath: '/checkout/pending'
      preLoaderRoute: typeof CheckoutPendingImport
      parentRoute: typeof rootRoute
    }
    '/checkout/recover': {
      id: '/checkout/recover'
      path: '/checkout/recover'
      fullPath: '/checkout/recover'
      preLoaderRoute: typeof CheckoutRecoverImport
      parentRoute: typeof rootRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessImport
      parentRoute: typeof rootRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/$slug_/checkin': {
      id: '/events/$slug_/checkin'
      path: '/events/$slug/checkin'
      fullPath: '/events/$slug/checkin'
      preLoaderRoute: typeof EventsSlugCheckinImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/submission-issues': typeof AdminSubmissionIssuesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/recover': typeof CheckoutRecoverRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/$slug/checkin': typeof EventsSlugCheckinRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/submission-issues': typeof AdminSubmissionIssuesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/recover': typeof CheckoutRecoverRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/$slug/checkin': typeof EventsSlugCheckinRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/payment': typeof PaymentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/submission-issues': typeof AdminSubmissionIssuesRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/pending': typeof CheckoutPendingRoute
  '/checkout/recover': typeof CheckoutRecoverRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$slug_/checkin': typeof EventsSlugCheckinRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/payment'
    | '/admin/coupons'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/products'
    | '/admin/submission-issues'
    | '/admin/submissions'
    | '/auth/register'
    | '/catalog/$id'
    | '/checkout/cancel'
    | '/checkout/pending'
    | '/checkout/recover'
    | '/checkout/success'
    | '/events/$slug'
    | '/admin'
    | '/catalog'
    | '/events'
    | '/events/$slug/checkin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/payment'
    | '/admin/coupons'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/products'
    | '/admin/submission-issues'
    | '/admin/submissions'
    | '/auth/register'
    | '/catalog/$id'
    | '/checkout/cancel'
    | '/checkout/pending'
    | '/checkout/recover'
    | '/checkout/success'
    | '/events/$slug'
    | '/admin'
    | '/catalog'
    | '/events'
    | '/events/$slug/checkin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/payment'
    | '/admin/coupons'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/products'
    | '/admin/submission-issues'
    | '/admin/submissions'
    | '/auth/register'
    | '/catalog/$id'
    | '/checkout/cancel'
    | '/checkout/pending'
    | '/checkout/recover'
    | '/checkout/success'
    | '/events/$slug'
    | '/admin/'
    | '/catalog/'
    | '/events/'
    | '/events/$slug_/checkin'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  PaymentRoute: typeof PaymentRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSubmissionIssuesRoute: typeof AdminSubmissionIssuesRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CatalogIdRoute: typeof CatalogIdRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutPendingRoute: typeof CheckoutPendingRoute
  CheckoutRecoverRoute: typeof CheckoutRecoverRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EventsSlugRoute: typeof EventsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsSlugCheckinRoute: typeof EventsSlugCheckinRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  PaymentRoute: PaymentRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSubmissionIssuesRoute: AdminSubmissionIssuesRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CatalogIdRoute: CatalogIdRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutPendingRoute: CheckoutPendingRoute,
  CheckoutRecoverRoute: CheckoutRecoverRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EventsSlugRoute: EventsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsSlugCheckinRoute: EventsSlugCheckinRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/cart",
        "/payment",
        "/admin/coupons",
        "/admin/events",
        "/admin/login",
        "/admin/media",
        "/admin/products",
        "/admin/submission-issues",
        "/admin/submissions",
        "/auth/register",
        "/catalog/$id",
        "/checkout/cancel",
        "/checkout/pending",
        "/checkout/recover",
        "/checkout/success",
        "/events/$slug",
        "/admin/",
        "/catalog/",
        "/events/",
        "/events/$slug_/checkin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/payment": {
      "filePath": "payment.tsx"
    },
    "/admin/coupons": {
      "filePath": "admin/coupons.tsx"
    },
    "/admin/events": {
      "filePath": "admin/events.tsx"
    },
    "/admin/login": {
      "filePath": "admin/login.tsx"
    },
    "/admin/media": {
      "filePath": "admin/media.tsx"
    },
    "/admin/products": {
      "filePath": "admin/products.tsx"
    },
    "/admin/submission-issues": {
      "filePath": "admin/submission-issues.tsx"
    },
    "/admin/submissions": {
      "filePath": "admin/submissions.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/catalog/$id": {
      "filePath": "catalog/$id.tsx"
    },
    "/checkout/cancel": {
      "filePath": "checkout/cancel.tsx"
    },
    "/checkout/pending": {
      "filePath": "checkout/pending.tsx"
    },
    "/checkout/recover": {
      "filePath": "checkout/recover.tsx"
    },
    "/checkout/success": {
      "filePath": "checkout/success.tsx"
    },
    "/events/$slug": {
      "filePath": "events/$slug.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/catalog/": {
      "filePath": "catalog/index.tsx"
    },
    "/events/": {
      "filePath": "events/index.tsx"
    },
    "/events/$slug_/checkin": {
      "filePath": "events/$slug_.checkin.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
